config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tools do
    resources :bookings, only: %i[new create show]
  end

  get "/dashboard", to: "pages#dashboard"
  get "/profile", to: "pages#profile" # profile_path
  # Defines the root path route ("/")
  # root "articles#index"
end

# /tools                        GET	tools     index
# /tools/:id	                  GET	tools     show
# /tools/:tool_id/bookings/new	GET	bookings	new
# /tools/:id/edit               GET	tools	    edit
# /tools/:tool_id/bookings/:id  GET	bookings	show

# tool_bookings POST   /tools/:tool_id/bookings(.:format)
# bookings#create
# new_tool_booking GET    /tools/:tool_id/bookings/new(.:format)
# bookings#new
#    tool_booking GET    /tools/:tool_id/bookings/:id(.:format)
# bookings#show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool

  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }

  def total_earnings
    rental_days = (end_date - start_date).to_i
    rental_days * tool.price
  end

  def total_payments
    rental_days = (end_date - start_date).to_i
    rental_days * tool.price
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, :price, presence: true
  validates :price, numericality: true
  #comment empty
  def booked_dates
    bookings.map do |booking|
      (booking.start_date..booking.end_date).map { |date| date.strftime("%Y-%m-%d") }
    end.flatten
  end

  include PgSearch::Model
  pg_search_scope :search_name_city_description,
    against: [ :name, :city, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :tools, dependent: :destroy
  has_many :bookings, dependent: :destroy

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_tool, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.tool = @tool # the one we set in the private method below
    if @booking.save
      redirect_to tool_booking_path(@tool, @booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @total_payments = @booking.total_payments
    @image_url = @booking.tool.image_url
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_tool
    @tool = Tool.find(params[:tool_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @no_navbar = true
  end

  def dashboard
    @bookings = current_user.bookings
    # @lent_tools =
    @tools = current_user.tools
    @received_bookings = @tools.map { |tool| tool.bookings }.flatten
  end

  def profile
    @user = current_user

  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def show
    @tool = Tool.find(params[:id])
  end

  def index
    if params[:query].present?
      @tools = Tool.search_name_city_description(params[:query])
      if @tools.empty?
        flash.now[:notice] = "No results found for '#{params[:query]}'. please check your input!"
      end
    else
      @tools = Tool.all
    end
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tool_path(@tool)
      flash.now[:success] = "The Tool has been created"
    else
      flash.now[:error] = "Your data is not saved. Please provide valid data and try again."
      render :new
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :image_url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="text-center my-5">Book <%= @tool.name %> </h1>

  <div>
    <%= simple_form_for [@tool, @booking], data: { controller: 'flatpickr', 'flatpickr-booked-value': @tool.booked_dates.to_json } do |f| %>
      <%= f.input :start_date, required: false, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
      <%= f.input :end_date, required: false, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
      <div class="mb-3">Price per day: <%= number_to_currency(@tool.price, unit: "€", separator: ",") %></div>
      <%= f.submit "Book!", class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="booking-card">
    <div class="booking-text mx-3 my-5">
      <h3 class="card-text my-4 pt-4"><strong>Thanks for booking the <%= @booking.tool.name %></strong></h3>
      <div class="d-flex justify-content-center">
        <p class="card-title my-4">Your Total Payment is: <%= @total_payments.round(2) %>€</p>
      </div>
      <div class="card-body d-flex flex-column justify-between align-items-center">
        <%= image_tag @image_url, class: "img-fluid mb-3", style: "width: 300px; height: 300px;" %>

        <div class="d-flex justify-content-center my-3">
          <%= link_to 'Go To Dashboard', dashboard_path, class: "btn btn-flat" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toolbox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%# <p class="notice"><%= notice %>
    <%# </p> %>
    <p class="alert"><%= alert %></p>
    <% unless @no_navbar %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container my-4 py-2 ">
  <h1>Dashboard</h1>

  <h2>Upcoming Bookings</h2>
  <% @bookings.each do |booking| %>
    <div class="card p-4 my-3">
      <div class="d-flex justify-content-between 100w p-2">
        <h3>Hooray! You've booked a <%= booking.tool.name %> from <%= booking.tool.user.firstname %></h3>
        <img class="avatar-bordered" alt="avatar-bordered" src="https://media.istockphoto.com/id/1337144146/de/vektor/standard-avatar-profilsymbolvektor.jpg?s=170667a&w=0&k=20&c=P_OBjasv808q0FKQky9KwCnApsblnOd_gOaQfnzwLnE=">
      </div>
      <div class="d-flex justify-content-between 100w p-4 my-3 align-items-center">
        <div class= "d-flex">
          <img src= <%= booking.tool.image_url%> class="dashboard-img me-3">
          <div>
            <p><strong>Starting from:</strong><%= booking.start_date.strftime("%a, %e %b %Y") %></p>
            <p><strong>Until:</strong><%= booking.end_date.strftime("%a, %e %b %Y") %></p>
          </div>
        </div>
        <p class="pricetag">Price in total: <strong><%= booking.tool.price * (booking.end_date - booking.start_date).to_i.round(2) %>€</strong></p>
      </div>
    </div>
  <% end %>

  <h2>Your offered tools</h2>

  <div class="row">
    <% @tools.each do |tool| %>
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <%= link_to tool_path(tool), class: "card h-100" do %>
          <img src="<%= tool.image_url %>" class="card-img-top" alt="<%= tool.name %>">
          <div class="card-body d-flex justify-content-between">
            <h5 class="card-title"><%= tool.name %></h5>
            <h5 class="card-title"><%= tool.city %></h5>
            <p class="card-text"><%= number_to_currency(tool.price, unit: "€", separator: ",") %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <h2>Who booked your tools?</h2>

  <% if @received_bookings.present? %>
    <% @received_bookings.each do |booking| %>
      <div class="card p-4 my-3">
        <div class="d-flex">
          <h3><%= booking.user.firstname %> booked a <%= booking.tool.name %> from you!</h3>
          <div class="container">
            <p><strong>Starting from:</strong><%= booking.start_date.strftime("%a, %e %b %Y") %></p>
            <p><strong>Until:</strong><%= booking.end_date.strftime("%a, %e %b %Y") %></p>
          </div>
          <p class="pricetag">Earnings in total: <strong><%= booking.tool.price * (booking.end_date - booking.start_date).to_i %>€</strong></p>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="card p-4 my-3">
      <p>Currently nobody has booked your tools.</p>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url('https://res.cloudinary.com/dwrkiuiqa/image/upload/v1677668759/sidney-pearce-WRgKwttuP7A-unsplash_k6oevr.jpg');">

  <div class="container">
    <div class="position-absolute top-0 end-0 m-4">
      <%= link_to "Login", new_user_session_path, class: "btn btn-ghost" %>
    </div>
    <div class="inner-container">
      <h1>Welcome to ToolBox!</h1>
      <p>Rent out your tools and rent any tool you may need for your next creativity journey</p>
      <%= link_to "Explore the ToolBox", tools_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container my-4 py-4">
  <div class="container-background">
    <h1>Your Profile</h1>
    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Username</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0"><%= @user.username %></p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Email</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0"><%= @user.email %></p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Full Name</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0"><%= @user.firstname %> <%= @user.lastname %></p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Mobile</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">(098) 765-4321</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Tools:</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                <% @user.tools.each do |tool| %>
                  <%= tool.name %>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dwrkiuiqa/image/upload/v1677668769/logo_mm1ynn.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "Rent Your Tool Out!", "/tools/new", class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Find Tools", "/tools", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://media.istockphoto.com/id/1337144146/de/vektor/standard-avatar-profilsymbolvektor.jpg?s=170667a&w=0&k=20&c=P_OBjasv808q0FKQky9KwCnApsblnOd_gOaQfnzwLnE=", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Your Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/tools/index.html.erb
<h1>Find Tools!</h1>
<div class="container">

  <div class="search">
      <%= form_with url: tools_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control me-3",
        placeholder: "Find a tool"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>

        <% if flash.now[:notice].present? %>
        <div class="alert alert-info mt-3">
          <%= flash.now[:notice] %>
        </div>
      <% end %>
  </div>

  <div class="row">
    <% @tools.each do |tool| %>
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <%= link_to tool_path(tool), class: "card h-100" do %>
          <img src="<%= tool.image_url %>" class="card-img-top" alt="<%= tool.name %>">
          <div class="card-body d-flex justify-content-between">
            <h5 class="card-title"><%= tool.name %></h5>
            <h5 class="card-title"><%= tool.city %></h5>
            <p class="card-text"><%= number_to_currency(tool.price, unit: "€", separator: ",") %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tools/new.html.erb
<h1>Add Your Tool</h1>

<div>
  <%= simple_form_for(@tool) do |f| %>
    <%= f.input :name, required: false %>
    <%= f.input :price, required: false %>
    <%= f.input :description, required: false %>
    <%= f.input :image_url, required: false %>
    <%= f.submit "Create Tool", class: "btn btn-flat" %>
  <% end %>
</div>

app/views/tools/show.html.erb
<div class="container">
  <div class="container-background d-flex my-4 py-4">
    <h1><%= @tool.name %></h1>
  </div>
    <div class="container-background d-flex">
      <div class="tool-img-container">
        <img src= <%= @tool.image_url%> class="tool-img">
      </div>
      <div class="tool-content">
        <div class="d-flex justify-content-between w-100">
          <div class="d-flex align-items-center title-wrapper">
            <img class="avatar-bordered" alt="avatar-bordered" src="https://media.istockphoto.com/id/1337144146/de/vektor/standard-avatar-profilsymbolvektor.jpg?s=170667a&w=0&k=20&c=P_OBjasv808q0FKQky9KwCnApsblnOd_gOaQfnzwLnE=">
            <h2><%= @tool.user.firstname %></h2>
          </div>
          <h2><%= number_to_currency(@tool.price, unit: "€", separator: ",") %></h2>
        </div>
        <p><%= @tool.description %></p>
        <%= link_to "Book now", new_tool_booking_path(@tool), class:"btn btn-flat" %>
      </div>
    </div>
</div>

<%# https://cdn.pixabay.com/photo/2015/07/28/20/55/tools-864983__480.jpg %>